id: kubernetes_kubeconfig
learningObjectives: 
- Configuring kubectl using kubeconfig file
hints:
- "Try the following command: `kubectl config get-contexts`"
startFlow:
  do:
  - actionId: bot_message
    params:
      person: devops
      messages:
      - text: "Great. Next, we need to configure kubectl so it can connect to our K8s cluster."
        delay: 800
      - text: "We do that using [kubeconfig](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) files. Just :instruction[tap on the `Download Kubeconfig` button in the left-hand side menu here in Snack to download your kubeconfig file.]"
        delay: 1500
      - text: "This will allow you to access your namespace in the K8s cluster. :instruction[Copy the file, or its contents, to `$HOME/.kube/config`]"
        delay: 1000
      - text: "Once you’ve configured kubectl, you can start running commands against the cluster. :instruction[Use kubectl to retrieve information about the kubectl contexts and **get back to me with the name of your namespace**.]"
        delay: 1000
trigger:
  type: user_message
  params: 
    person: devops
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: ${userMessageText}
          regex: ${user?.awsAnythink?.tenantName}
      then:
        do:
        - actionId: bot_message
          params:
            person: devops
            messages:
            - text: This seems correct!
              delay: 600
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: devops
            messages:
            - text: No, this looks incorrect. Are you sure you’ve configured kubectl with the correct kubeconfig?
              delay: 800
            - text: Don't "yes" me, check again what you might've done wrong.
              delay: 800
