id: kubernetes_deploy_with_helm
learningObjectives: 
- Use Helm to deploy to the Kubernetes cluster
hints:
- The command structure should be `helm install <release-name> <chart-dir> < --set key=value >`
- You can retreive the Ingress using kubectl
startFlow:
  do:
  - actionId: bot_message
    params:
      person: devops
      messages:
      - text: "Good. Now you need to run `helm install`. You need to pass a few paramaters to the command:"
        delay: 1200
      - text: First, the release name. Choose whatever you want. `anythink-market` would be a great choice.'
        delay: 800
      - text: Second, path to chart directory. You have a prepared directory in the project root folder
        delay: 800
      - text: And last, set the values `frontend.image.tag` and `backend.image.tag` used by Helm Charts to be `${Lodash.replace(Lodash.replace(user.repository, 'https://github.com/',''), "/", "-")}-latest`. This tells the deployment to use images that were already uploaded for you to our registry.
        delay: 800
      - text: If all goes well you should be able to access the application using the Ingress that is connected to the frontend
        delay: 1000
      - text: ":instruction[load any page in your frontend to continue]"
        delay: 500      
        
trigger:
  type: local_page_load
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: ${href}
          regex: ^https://anythink-market-
      then:    
        do:
        - actionId: bot_message
          params:
            person: devops
            messages:
            - text: It is suprising but it seems that everything is working as expected.
              delay: 2000
        - actionId: finish_step
        