id: kubernetes_install_kubectl
learningObjectives: 
- Installing kubectl
hints:
- To install kubectl on codespaces, follow the [instructions for Linux Debian-based distributions](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/).
startFlow:
  do:
  - actionId: bot_message
    params:
      person: devops
      messages:
      - text: "You haven’t been with us for a long time, but I believe it’s time to let you into our cloud environment. "
        delay: 1200        
      - text: "Not only that, you’re about to deploy to our Kubernetes cluster."
        delay: 1000
      - text: "Also, I’ll be **referring to it as K8s** from now on, because short terms are, well, shorter, and easier to write."
        delay: 1200
      - text: "Fun fact, it’s called K8s because there are 8 letters between the “K” and the “s” in Kubernetes."
        delay: 1000
      - text: "The first thing you need is to :instruction[install [kubectl](https://kubernetes.io/docs/tasks/tools/)]. Know that **we use kubectl to run commands against the K8s cluster.**"
        delay: 1500
      - text: "If it doesn’t make sense, don’t worry, it will really soon. But first, **make sure kubectl is installed and working**. Run `kubectl help` and make sure the list of supported commands is printed."
        delay: 1500
      - text: ":instruction[Let me know once you’ve finished installing and are ready to continue]" 
        delay: 1000
  - actionId: ready_message
    params:
      person: head-of-rd
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
