id: kubernetes_kubeconfig
learningObjectives: 
- Configuring kubectl using kubeconfig file
hints:
- "Try the following command: `kubectl config get-contexts`"
startFlow:
  do:
  - actionId: bot_message
    params:
      person: devops
      messages:
      - text: "Great. Next, we need to configure kubectl so it can connect to our Kubernetes cluster."
        delay: 800
      - text: "We do that using [kubeconfig](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) files. Just :instruction[tap on the `Download Kubeconfig` button in the left-hand side menu here in Snack to download your kubeconfig file.]"
        delay: 1200
      - text: "This will allow you to access to your namespace in the Kubernetes cluster. :instruction[Copy the file, or its contents, to `$HOME/.kube/config`]"
        delay: 1200
      - text: "Once you configured kubectl you can start running commands against the Kubernetes cluster. :instruction[Use kubectl to retrieve information about the kubectl contexts and **get back to me with the name of your namespace**]"
        delay: 1200
trigger:
  type: user_message
  params: 
    person: devops
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: ${userMessageText}
          regex: ${user?.awsAnythink?.tenantName}
      then:
        do:
        - actionId: bot_message
          params:
            person: devops
            messages:
            - text: This seems correct!
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: devops
            messages:
            - text: No, this looks incorrect. Are you sure you configured kubectl with the correct kubeconfig?
              delay: 2500
