id: kubernetes_install_helm
learningObjectives: 
- Installing Helm
hints:
- Follow the os-specific [installation instructions](https://helm.sh/docs/intro/install/). If you’re using Codespaces, follow the Debian/Ubuntu instructions.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: devops
      messages:
      - text: "It is time to deploy! We will use [Helm](https://helm.sh/) for that. Helm automates the complex process of deploying applications to K8s clusters."
        delay: 1000
      - text: "First, we need to :instruction[[install Helm](https://helm.sh/docs/intro/install/)]"
        delay: 1000
      - text: You should be able to run `helm` without `sudo`. If you use the `get_helm.sh` script, make sure to pass `--no-sudo` as an argument.
        delay: 1100
      - text: :instruction[Run `helm version` after the installation to verify it was successful.] 
        delay: 800
      - text: :instruction[**Let me know once you've finished installing and are ready to continue.**] 
        delay: 800
  - actionId: ready_message
    params:
      person: devops
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
