id: kubernetes_install_helm
learningObjectives: 
- Installing Helm
hints:
- Follow the [installation instructions](https://helm.sh/docs/intro/install/) according to the operatin system. Follow the Debian/Ubuntu instructions to install on Codespaces.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: devops
      messages:
      - text: "It is time to deploy. We will use [Helm](https://helm.sh/) for that. Helm automates the complex process of deploying applications to Kubernetes."
        delay: 1500
      - text: "First, we need to [install Helm](https://helm.sh/docs/intro/install/). Run `helm version` after the installation to verify it was uccessful"
        delay: 1500
      - text: ":instruction[Let me know once you finished installing and ready to continue]"
        delay: 1200
        
trigger:
  type: user_message
  params:
    person: devops
  flowNode:
    if:
      conditions:
        - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
          - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Umm, If you need any help, just let me know that you’re stuck. If that’s not the case - take your time and tell me once you're ready :)
                delay: 1000
